const NodeType = {
  PAGE_NODE: 'PAGE_NODE',
  TITLE_NODE: 'TITLE_NODE',
  SUBTITLE_NODE: 'SUBTITLE_NODE',
  FULL_NAME_NODE: 'FULL_NAME_NODE',
  EMAIL_NODE: 'EMAIL_NODE',
  PHONE_NODE: 'PHONE_NODE',
  STUDENT_ID_NODE: 'STUDENT_ID_NODE',
  PASSWORD_NODE: 'PASSWORD_NODE',
  CONFIRM_PASSWORD_NODE: 'CONFIRM_PASSWORD_NODE',
  GENDER_NODE: 'GENDER_NODE',
  DATE_OF_BIRTH_NODE: 'DATE_OF_BIRTH_NODE',
  COURSE_NODE: 'COURSE_NODE',
  YEAR_NODE: 'YEAR_NODE',
  TERMS_CHECKBOX_NODE: 'TERMS_CHECKBOX_NODE',
  BUTTON_NODE: 'BUTTON_NODE',
  THEME_NODE: 'THEME_NODE',
  BACKGROUND_NODE: 'BACKGROUND_NODE'
};

function createNode(type, value, line) {
  return { type, value, line };
}

module.exports = {
  NodeType,
  createNode
};
